OpenAIModel:
  model: "gpt-3.5-turbo"
  api_key: "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"

GLMModel:
  model_url: "your_chatglm_model_url"
  timeout: 300

common:
  book: "/Users/zheng/ai/openai-quickstart/openai-translator/tests/test.pdf"
  file_format: "pdf"